
# To start a new game
POST http://localhost:3000/api/games HTTP/1.1
Content-Type: application/json

{
    "type": 0,
    "user1": {
        "email": "asadalikanwal@mum.edu",
        "result": null,
        "done": false
    },
    "user2": {
        "email": "asadalikanwal@mum.edu",
        "result": null,
        "done": false
    },
    "questions": [
        {
            "header": "An institution for educating children",
            "answer": "school",
            "options": ["home, hospital, school"],
            "question_result": {
               "user1": null,
               "user2": null
            }
        }
    ],
    "winner": ""
}

###

# To find a game
GET http://localhost:3000/api/games/5dabe43fa55b5e11399b52212 HTTP/1.1


###
{
    "type": 0,
    "user1": {
        "email": "asadalikanwal@mum.edu",
        "result": null,
        "done": false
    },
    "user2": {
        "email": "asadalikanwal@mum.edu",
        "result": null,
        "done": false
    },
    "questions": [
        {
            "header": "An institution for educating children",
            "answer": "school",
            "options": ["home, hospital, school"],
            "question_result": {
                "user1": "",
                "user2": "",
            }

        }
    ],
    "winner": ""
}
