#Add User
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "email": "shiva@mum.edu",
    "password": "123456"
}

###

#Get User by Email/ Email Verification
GET http://localhost:3000/api/users/asadalikanwal@mum.edu HTTP/1.1

###



#Get all users with access token
GET http://localhost:3000/api/users/ HTTP/1.1
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGFiZTA2YmZiN2FhYjBmM2Y3OTMwMTgiLCJlbWFpbCI6InNoaXZhQG11bS5lZHUiLCJpYXQiOjE1NzE1NDUyMDYsImV4cCI6MTU3MTU0ODgwNn0.dbifOpmAweblCrpAtAZ_3XyaAAn-4_QHYny_me_mXiQ; Max-Age=86400; Path=/; Expires=Mon, 21 Oct 2019 04:20:06 GMT; HttpOnly
###



# Login
POST http://localhost:3000/auth HTTP/1.1
Content-Type: application/json

{
    "email": "shiva@mum.edu",
    "password": "123456"
}