POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "email": "asadalikanwal@mum.edu",
    "password": "123456"
}

###

GET http://localhost:3000/users/asadalikanwal@mum.edu HTTP/1.1

###

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "aakanwal@mum.edu",
    "password": "123456"
}