// Search for word (vocabulary)
GET https://localhost:3000/api/search/pen HTTP/1.1
Cookie:access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGFjYjhhYjAzY2ExZjExYjg5OTAzMDEiLCJlbWFpbCI6InRhaG1lZEBtdW0uZWR1IiwiaWF0IjoxNTcxNjg3MzkwLCJleHAiOjE1NzE2OTA5OTB9.P-84868cDMuzBe9P_dI1gDyt5fr_kads6NeN7wJCzhE; Max-Age=86400; Path=/; Expires=Tue, 22 Oct 2019 19:49:50 GMT; HttpOnly
    // need to add the credentials(JWT) to the request.


###
GET https://localhost:3000/api/search/ HTTP/1.1
Cookie:access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGFhMzVhZmI1MWZmODVlOTJlNjhmYTIiLCJlbWFpbCI6ImFha2Fud2FsQG11bS5lZHUiLCJpYXQiOjE1NzE3NTk4NjUsImV4cCI6MTU3MTc2MzQ2NX0.DKQXlpCtIEsQSmRdpYim1iZDW0zebwqDlQcdtQ_mRTY; Max-Age=86400; Path=/; Expires=Wed, 23 Oct 2019 15:57:45 GMT; HttpOnly